// Flat ESLint config for apps/frontend (feature 006 T003).
//
// Uses the Next.js compatibility shim to load `eslint-config-next` (which is
// still legacy/eslintrc) inside ESLint 9.x flat config. This is the pattern
// the Next.js docs recommend until `eslint-config-next` itself ships a flat
// export.

import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "playwright-report/**",
      "test-results/**",
      "next-env.d.ts", // auto-generated by Next.js
    ],
  },
  {
    rules: {
      // Allow inline `style` for now (existing components use it heavily).
      // Future cleanup task: migrate to Tailwind classes.
      "react/no-unknown-property": "off",
      // Allow `_var` to opt-out of unused-vars per TS convention.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default config;
