"""Pydantic v2 schemas shared across Clean Match Chess packages."""

from shared_types.audit_run import (
    AccountProfile,
    AuditRun,
    CrossGamePattern,
    EngineFingerprint,
    RunError,
    RunErrorCode,
    RunMode,
    RunStatus,
)
from shared_types.game import (
    CandidateMove,
    ComplexityScore,
    Game,
    Move,
    MoveClassification,
    PlayerColor,
    PlayerRef,
    Position,
    Result,
    TimeControl,
    TimeControlCategory,
)
from shared_types.report import (
    FlaggedSegment,
    HostInfo,
    Narrative,
    ReportBundle,
    ReportFormat,
    ReportLanguage,
    ReproducibilityManifest,
)
from shared_types.score import (
    PLY_MIN_FOR_SCORING,
    RISK_HIGH_MIN,
    RISK_LOW_MAX,
    RISK_MEDIUM_MAX,
    RiskLevel,
    SuspicionScore,
    risk_level_for,
)
from shared_types.signal import (
    HeuristicVersion,
    Phase,
    Regime,
    Segment,
    SignalAggregate,
    SignalContribution,
)

__all__ = [
    "PLY_MIN_FOR_SCORING",
    "RISK_HIGH_MIN",
    "RISK_LOW_MAX",
    "RISK_MEDIUM_MAX",
    "AccountProfile",
    "AuditRun",
    "CandidateMove",
    "ComplexityScore",
    "CrossGamePattern",
    "EngineFingerprint",
    "FlaggedSegment",
    "Game",
    "HeuristicVersion",
    "HostInfo",
    "Move",
    "MoveClassification",
    "Narrative",
    "Phase",
    "PlayerColor",
    "PlayerRef",
    "Position",
    "Regime",
    "ReportBundle",
    "ReportFormat",
    "ReportLanguage",
    "ReproducibilityManifest",
    "Result",
    "RiskLevel",
    "RunError",
    "RunErrorCode",
    "RunMode",
    "RunStatus",
    "Segment",
    "SignalAggregate",
    "SignalContribution",
    "SuspicionScore",
    "TimeControl",
    "TimeControlCategory",
    "risk_level_for",
]
